### ISSUE TITLE
Add `.do.submit`

### ISSUE THREAD

**Issue by monolithed** [nodeca/navit#31]
@puzrin, I have a simple test to submit form. Test fails after asserting exception on the same url.

https://github.com/monolithed/navit/commit/7ba5cbade8ea3e441a8f9b41aac5094d474e8485

Actual:

``` js
assert.equal(url, 'http://localhost:17345/test/fixtures/do/back.html'); 
// url — 'http://localhost:17345/test/fixtures/do/submit.html'
```

Expected:

``` js
assert.equal(url, 'http://localhost:17345/test/fixtures/do/back.html'); 
// url — 'http://localhost:17345/test/fixtures/do/back.html'
```

**Comment by monolithed** [comment]
The problem is actual only for `phantomjs`

**Comment by puzrin** [comment]
I'm not sure it will work, because browser will leave page after the POST.

I'd say that's related to your implementation rather than `navit`.

**Comment by monolithed** [comment]
So, how to test one?

**Comment by puzrin** [comment]
That's a good question. Problem is that we can not guarantee anything about submit:
- we do not know anything about POST reply format, only status code.
- submit can be intercepted by javascript, and we can not say if page was really reloaded, or processed via ajax.

Need to check how other frameworks (casper, ...) care about that. I'd suggest something like eval + wait + status check.

Try to summarize, what do you expect from `.do.submit()` in chained form. May be it's time to include it into core (if it possible to do it in generic form).

**Comment by monolithed** [comment]
My use-case:

``` js
browser
    .open('/user/login')
    .wait('form[name="login"]')
    .type('input[name="Username"]', user.email)
    .type('input[name="Password"]', user.password)
    .submit('form[name="login"]')
    // ...
```

But would be nice to have something like:

``` js
return browser
    .open('/user/login')
    .wait('form[name="login"]')
    .fill('form[name="login"]', {
        Username: user.email,
        Password: user.password
    }, true)
```

I've the `fill` implementation https://github.com/monolithed/navit/commit/7ba5cbade8ea3e441a8f9b41aac5094d474e8485. But could not test as well

**Comment by puzrin** [comment]
You missed important info - what do you need AFTER submit/fill. As i explained before, it's impossible to magically decide what is "success". Only if you hardcode your known cases.

Now you can write:

``` js
.do.click('submit button selector')
.wait(1) // or wait for selector, if new page has something special
// here you can check status code, selector and so on
```

AFAIK, that should work. I know `.wait(...)` is scary, but that's because we don't know what happens after submit click.

**Comment by monolithed** [comment]
``` html
<form action="/login">
    <input name="Username" />
    <input name="Password" />
</form>
```

How to send the form data without any buttons?

**Comment by puzrin** [comment]
> How to send the form without any buttons?
- For server unit-testing, you can do it by direct POST request. `.open()` should supports it via options.
- For integration test, problem is not "how to sent form" from user interface, but "how to wait for result". I'm not sure that universal solution is possible. We use kludge `.click()` + `.wait()`

I had no cases with massive form send from user interface, and may be not familiar with common practices. Feel free to point me ones, if you know. By default i dig in casper API, when need something special. Here is what they have http://docs.casperjs.org/en/latest/modules/casper.html#fill

**Comment by monolithed** [comment]
> For integration test, problem is not "how to sent form" from user interface, but "how to wait for result". I'm not sure that universal solution is possible. We use klugde .click() + .wait()

What is the difference between `submit` and `click`? The GET/POST request will be sent in all cases and `wait` is expected.

> I had no cases with massive form send from user interface, and may be not familiar with common practices. Feel free to point me ones, if you know. 

It's standard practice to test when user presses `enter` in a form.  And in many cases, I have no events on buttons only one `submit` event.

> By default i dig in casper API, when need something special. Here is what they have http://docs.casperjs.org/en/latest/modules/casper.html#fill

Yup, I saw it. Would nice to have one :)

**Comment by puzrin** [comment]
> What is the difference between submit and click? The GET/POST request will be sent in all cases and wait is expected.

if you expect chained `.wait()` after, then there is no difference (from my point of view). That's why we did not implemented `.submit()` - it does not add value (as far as i understand). If i'm wrong - let me know, that's discussable.

> Yup, I saw it. Would nice to have one :)

The only reason why `.fill()` does not exist here - time restrictions. Our form cases are very simple, and it was enougth for us to use `.type()`. We care seriously about right design and extendibility, but have to shrink basic features sometime. If anyone will decide to spend time and implement casper-like fill methods, such PR will be accepted ASAP.

**Comment by monolithed** [comment]
> if you expect chained .wait() after, then there is no difference (from my point of view). That's why we did not implemented .submit() - it does not add value (as far as i understand). 

The form can be sent via Ajax and `wait` is a good indicator to check the submission status

> If i'm wrong - let me know, that's discussable.

I'm trying to say there's a standard practice to use a submit event listener when form is submitted. And the same method should be used to test form submission.

For example:

``` html
  <form action="login" name="login">
    <input type="text" name="username" />
    <input type="password" name="password" />
    <input type="submit" name="submit" />
  </form>
```

Good code:

``` js
document.forms.login.addEventListener('submit', event => { });
```

Bad code:

``` js
document.forms.login.elements.submit.addEventListener('click', event => { });
```

No one uses the second code. 
I hope I have clearly explained what I mean :)

**Comment by puzrin** [comment]
I see no separate `.submit()` method in casper's ajax api. But IMHO, it's not a problem to implement submit event in `.fill(..., true)` if that's really needed.

My short summary for this issue is:
- Example in first post is not a navit bug.
- Current API allows to do form operations via kludge `.type()` + `.click()`. We do not force it as the best and right way, but if you need it right now - that's possible.
- Yes, it would be nice to have `.fill()` but implementation is left for volunteers, because we have no time to do it in the nearest future.
- We still support `navit`, and if someone need internals improvement to add some features, that will be done fast (99% of extensions do not need any changes in core).

**Comment by puzrin** [comment]
Close: `.submit` should be a part of `.fill`
