### ISSUE TITLE
Hooks for custom assertion libraries?

### ISSUE THREAD

**Issue by inca** [nodeca/navit#6]
Hi, guys,

Is it possible to use something like Chai alongside `test.evaluate` in Navit?

Currently we can only assert trivial cases (element existence, visibility, text, attributes, etc.) with Navit DSL, but asserting anything else (e.g. `jQuery.data()`, selections, ranges or virtually anything related to client scripting) is currently possible via `test.evaluate` which does not provide us with much information on failures — only that "evaluated function should return true".

TIA

**Comment by puzrin** [comment]
That depends. You can get any serializable data via `get.evaluate`. In nodeca with `nightmare` we did assersions pass via global handlers, but solution was very dirty.

https://github.com/nodeca/nodeca.core/commit/224c41ed715345ffb7a759b1cecc647db048ab17

**Comment by puzrin** [comment]
I have no objections against adding in-browser exceptions handler, but don't like that implementation as "official"

**Comment by inca** [comment]
Got it, so I guess I'll stick with retrieving data with `.get.evaluate`, then asserting it in a callback. Thanks!

**Comment by puzrin** [comment]
May be we just need better reporting (show real value instead of "evaluated function should return true") ? We already have such pending problem with testing against regex-es https://github.com/nodeca/navit/issues/1#issue-69352318

Could you describe scenarios, what you need to test and what you need to pass back?
